using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MRSTW.DataAccessLayer.Migrations.BusinessProfilesMigrations
{
    /// <inheritdoc />
    public partial class ReorderBusinessProfilesColumnsDisplayOrder : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE \"BusinessProfiles\" RENAME TO \"BusinessProfiles__OldOrder\";");

            migrationBuilder.Sql(@"
                CREATE TABLE ""BusinessProfiles__Reordered"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""UserId"" integer NOT NULL,
                    ""CompanyName"" character varying(200) NOT NULL,
                    ""ContactPerson"" character varying(150) NULL,
                    ""ResponsiblePerson"" character varying(150) NULL,
                    ""Email"" character varying(150) NULL,
                    ""PhoneNumber"" character varying(30) NOT NULL,
                    ""LocationAdress"" character varying(200) NULL,
                    ""IdnoCode"" character varying(50) NOT NULL,
                    ""EoriCode"" character varying(50) NULL,
                    ""TvaCode"" character varying(50) NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    CONSTRAINT ""PK_BusinessProfiles__Reordered"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_BusinessProfiles__Reordered_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE
                );
            ");

            migrationBuilder.Sql(@"
                INSERT INTO ""BusinessProfiles__Reordered"" (
                    ""Id"", ""UserId"", ""CompanyName"", ""ContactPerson"", ""ResponsiblePerson"",
                    ""Email"", ""PhoneNumber"", ""LocationAdress"", ""IdnoCode"", ""EoriCode"", ""TvaCode"", ""CreatedAt""
                )
                SELECT
                    ""Id"", ""UserId"", ""CompanyName"", ""ContactPerson"", ""ResponsiblePerson"",
                    ""Email"", ""PhoneNumber"", ""LocationAdress"", ""IdnoCode"", ""EoriCode"", ""TvaCode"", ""CreatedAt""
                FROM ""BusinessProfiles__OldOrder"";
            ");

            migrationBuilder.Sql(@"
                SELECT setval(
                    pg_get_serial_sequence('""BusinessProfiles__Reordered""', 'Id'),
                    COALESCE((SELECT MAX(""Id"") FROM ""BusinessProfiles__Reordered""), 0) + 1,
                    false
                );
            ");

            migrationBuilder.Sql("DROP TABLE \"BusinessProfiles__OldOrder\";");

            migrationBuilder.Sql("ALTER TABLE \"BusinessProfiles__Reordered\" RENAME TO \"BusinessProfiles\";");

            migrationBuilder.Sql("ALTER TABLE \"BusinessProfiles\" RENAME CONSTRAINT \"PK_BusinessProfiles__Reordered\" TO \"PK_BusinessProfiles\";");

            migrationBuilder.Sql("ALTER TABLE \"BusinessProfiles\" RENAME CONSTRAINT \"FK_BusinessProfiles__Reordered_Users_UserId\" TO \"FK_BusinessProfiles_Users_UserId\";");

            migrationBuilder.Sql("CREATE UNIQUE INDEX \"IX_BusinessProfiles_UserId\" ON \"BusinessProfiles\" (\"UserId\");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE \"BusinessProfiles\" RENAME TO \"BusinessProfiles__CurrentOrder\";");

            migrationBuilder.Sql(@"
                CREATE TABLE ""BusinessProfiles__OldLayout"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""UserId"" integer NOT NULL,
                    ""CompanyName"" character varying(200) NOT NULL,
                    ""IdnoCode"" character varying(50) NOT NULL,
                    ""ContactPerson"" character varying(150) NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""Email"" character varying(150) NULL,
                    ""EoriCode"" character varying(50) NULL,
                    ""PhoneNumber"" character varying(30) NOT NULL,
                    ""TvaCode"" character varying(50) NULL,
                    ""ResponsiblePerson"" character varying(150) NULL,
                    ""LocationAdress"" character varying(200) NULL,
                    CONSTRAINT ""PK_BusinessProfiles__OldLayout"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_BusinessProfiles__OldLayout_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE
                );
            ");

            migrationBuilder.Sql(@"
                INSERT INTO ""BusinessProfiles__OldLayout"" (
                    ""Id"", ""UserId"", ""CompanyName"", ""IdnoCode"", ""ContactPerson"", ""CreatedAt"",
                    ""Email"", ""EoriCode"", ""PhoneNumber"", ""TvaCode"", ""ResponsiblePerson"", ""LocationAdress""
                )
                SELECT
                    ""Id"", ""UserId"", ""CompanyName"", ""IdnoCode"", ""ContactPerson"", ""CreatedAt"",
                    ""Email"", ""EoriCode"", ""PhoneNumber"", ""TvaCode"", ""ResponsiblePerson"", ""LocationAdress""
                FROM ""BusinessProfiles__CurrentOrder"";
            ");

            migrationBuilder.Sql(@"
                SELECT setval(
                    pg_get_serial_sequence('""BusinessProfiles__OldLayout""', 'Id'),
                    COALESCE((SELECT MAX(""Id"") FROM ""BusinessProfiles__OldLayout""), 0) + 1,
                    false
                );
            ");

            migrationBuilder.Sql("DROP TABLE \"BusinessProfiles__CurrentOrder\";");

            migrationBuilder.Sql("ALTER TABLE \"BusinessProfiles__OldLayout\" RENAME TO \"BusinessProfiles\";");

            migrationBuilder.Sql("ALTER TABLE \"BusinessProfiles\" RENAME CONSTRAINT \"PK_BusinessProfiles__OldLayout\" TO \"PK_BusinessProfiles\";");

            migrationBuilder.Sql("ALTER TABLE \"BusinessProfiles\" RENAME CONSTRAINT \"FK_BusinessProfiles__OldLayout_Users_UserId\" TO \"FK_BusinessProfiles_Users_UserId\";");

            migrationBuilder.Sql("CREATE UNIQUE INDEX \"IX_BusinessProfiles_UserId\" ON \"BusinessProfiles\" (\"UserId\");");
        }
    }
}
