using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MRSTW.DataAccessLayer.Migrations.PackagesMigrations
{
    
    public partial class ReorderPackagesColumnsDisplayOrder : Migration
    {
        
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE \"Packages\" RENAME TO \"Packages__OldOrder\";");

            migrationBuilder.Sql(@"
                CREATE TABLE ""Packages__Reordered"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""UserId"" integer NULL,
                    ""Status"" character varying(50) NOT NULL,
                    ""TrackingCode"" character varying(100) NOT NULL,
                    ""FullName"" character varying(150) NULL,
                    ""CompanyName"" character varying(200) NULL,
                    ""ContactPerson"" character varying(150) NULL,
                    ""PhoneNumber"" character varying(30) NOT NULL,
                    ""LocationAdress"" character varying(200) NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    CONSTRAINT ""PK_Packages__Reordered"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_Packages__Reordered_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"")
                );
            ");

            migrationBuilder.Sql(@"
                INSERT INTO ""Packages__Reordered"" (
                    ""Id"", ""UserId"", ""Status"", ""TrackingCode"", ""FullName"",
                    ""CompanyName"", ""ContactPerson"", ""PhoneNumber"", ""LocationAdress"", ""CreatedAt""
                )
                SELECT
                    ""Id"", ""UserId"", ""Status"", ""TrackingCode"", ""FullName"",
                    ""CompanyName"", ""ContactPerson"", ""PhoneNumber"", ""LocationAdress"", ""CreatedAt""
                FROM ""Packages__OldOrder"";
            ");

            migrationBuilder.Sql(@"
                SELECT setval(
                    pg_get_serial_sequence('""Packages__Reordered""', 'Id'),
                    COALESCE((SELECT MAX(""Id"") FROM ""Packages__Reordered""), 0) + 1,
                    false
                );
            ");

            migrationBuilder.Sql("DROP TABLE \"Packages__OldOrder\";");

            migrationBuilder.Sql("ALTER TABLE \"Packages__Reordered\" RENAME TO \"Packages\";");

            migrationBuilder.Sql("ALTER TABLE \"Packages\" RENAME CONSTRAINT \"PK_Packages__Reordered\" TO \"PK_Packages\";");

            migrationBuilder.Sql("ALTER TABLE \"Packages\" RENAME CONSTRAINT \"FK_Packages__Reordered_Users_UserId\" TO \"FK_Packages_Users_UserId\";");

            migrationBuilder.Sql("CREATE INDEX \"IX_Packages_UserId\" ON \"Packages\" (\"UserId\");");
        }

        
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE \"Packages\" RENAME TO \"Packages__CurrentOrder\";");

            migrationBuilder.Sql(@"
                CREATE TABLE ""Packages__OldLayout"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""TrackingCode"" character varying(100) NOT NULL,
                    ""FullName"" character varying(150) NULL,
                    ""PhoneNumber"" character varying(30) NOT NULL,
                    ""LocationAdress"" character varying(200) NOT NULL,
                    ""Status"" character varying(50) NOT NULL,
                    ""UserId"" integer NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""CompanyName"" character varying(200) NULL,
                    ""ContactPerson"" character varying(150) NULL,
                    CONSTRAINT ""PK_Packages__OldLayout"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_Packages__OldLayout_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"")
                );
            ");

            migrationBuilder.Sql(@"
                INSERT INTO ""Packages__OldLayout"" (
                    ""Id"", ""TrackingCode"", ""FullName"", ""PhoneNumber"", ""LocationAdress"",
                    ""Status"", ""UserId"", ""CreatedAt"", ""CompanyName"", ""ContactPerson""
                )
                SELECT
                    ""Id"", ""TrackingCode"", ""FullName"", ""PhoneNumber"", ""LocationAdress"",
                    ""Status"", ""UserId"", ""CreatedAt"", ""CompanyName"", ""ContactPerson""
                FROM ""Packages__CurrentOrder"";
            ");

            migrationBuilder.Sql(@"
                SELECT setval(
                    pg_get_serial_sequence('""Packages__OldLayout""', 'Id'),
                    COALESCE((SELECT MAX(""Id"") FROM ""Packages__OldLayout""), 0) + 1,
                    false
                );
            ");

            migrationBuilder.Sql("DROP TABLE \"Packages__CurrentOrder\";");

            migrationBuilder.Sql("ALTER TABLE \"Packages__OldLayout\" RENAME TO \"Packages\";");

            migrationBuilder.Sql("ALTER TABLE \"Packages\" RENAME CONSTRAINT \"PK_Packages__OldLayout\" TO \"PK_Packages\";");

            migrationBuilder.Sql("ALTER TABLE \"Packages\" RENAME CONSTRAINT \"FK_Packages__OldLayout_Users_UserId\" TO \"FK_Packages_Users_UserId\";");

            migrationBuilder.Sql("CREATE INDEX \"IX_Packages_UserId\" ON \"Packages\" (\"UserId\");");
        }
    }
}
